[package]
name = "macro-map"
version = "0.2.0"
edition = "2021"
description = "Closure-less `Result::map_err` and `Option::ok_or_else`."
license = "MIT"
keywords = ["macros", "map", "error-handling"]

[dependencies]

[dev-dependencies]
postfix-macros = "0.1"
